services:
  web_ui:
    build:
      context: .
    container_name: client_app
    command: ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
    tty: true
    ports:
      - 8081:80

    networks:
      app_net:
        ipv4_address: 172.31.2.10

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.2.0/24
