version: '3.8'

services:
  mysql:
    container_name: moodle_database
    image: mysql
    ports:
      - 3308:3306
    restart: always
    volumes:
      - C:/Moodle/Moodle_db:/var/lib/mysql
      - C:/Moodle/Moodle_data:/var/www/moodledata
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepassword
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    networks:
      net: 
        ipv4_address: 172.29.1.2

  web:
    build:
      context: .
    container_name: moodle_www
    command: ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
    tty: true
    ports:
      - 84:80
    volumes:
      - C:/Moodle/Moodle_code:/var/www/html
      - C:/Moodle/Moodle_data:/var/www/moodledata
    networks:
      net:
        ipv4_address: 172.29.1.3

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.1.0/24
