services:
  web_service:
    build:
      context: .
    container_name: app_server
    command: ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
    tty: true
    ports:
      - 8080:80

    networks:
      custom_net:
        ipv4_address: 172.31.1.5

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.1.0/24
